# Generated by Django 4.0.2 on 2022-02-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_f_name_emplyee_usereg_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_designation', models.CharField(max_length=100)),
                ('Emp_code', models.IntegerField()),
                ('Emp_department', models.CharField(max_length=50)),
                ('Emp_skills', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='emplyee_usereg',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
