# Generated by Django 4.0.2 on 2022-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_employees_profile_emp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee_usereg',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
