# Generated by Django 4.0.2 on 2022-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee_usereg',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
