# Generated by Django 4.0.2 on 2022-02-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_alter_emplyee_usereg_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee_usereg',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
    ]
