# Generated by Django 4.0.2 on 2022-02-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_alter_emplyee_usereg_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='Employee_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.emplyee_usereg'),
        ),
    ]
