# Generated by Django 4.0.2 on 2022-02-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_employee_profile_employee_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dob', models.DateField(max_length=8)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone_no', models.CharField(max_length=50)),
                ('Emp_designation', models.CharField(max_length=100)),
                ('Emp_department', models.CharField(max_length=50)),
                ('Emp_skills', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EmplyeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Emp_code', models.CharField(max_length=300)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee_profile',
        ),
        migrations.DeleteModel(
            name='emplyee_usereg',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='Employee_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='emp.emplyeeregistration'),
        ),
    ]
