# Generated by Django 4.0.2 on 2022-03-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_employeeprofile_emplyeeregistration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='Emp_skills',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='Employee_reg',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='Employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.emplyeeregistration'),
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('profile', models.ManyToManyField(to='emp.EmployeeProfile')),
            ],
        ),
    ]
