# Generated by Django 4.0.2 on 2022-03-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_remove_employeeprofile_emp_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Employees',
            new_name='Employee',
        ),
    ]
