# Generated by Django 4.0.2 on 2022-03-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_rename_employees_employeeprofile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskills',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.emplyeeregistration'),
        ),
    ]
