# Generated by Django 4.0.2 on 2022-03-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0014_employeeskills_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Emp_department',
            new_name='employee_department',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Emp_designation',
            new_name='employee_designation',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Phone_no',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='employeeskills',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='emplyeeregistration',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='emplyeeregistration',
            old_name='Emp_code',
            new_name='emp_code',
        ),
        migrations.RenameField(
            model_name='emplyeeregistration',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='emplyeeregistration',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='emplyeeregistration',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='emplyeeregistration',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='profile',
        ),
    ]
