# Generated by Django 4.0.2 on 2022-03-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_rename_dob_employeeprofile_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplyeeregistration',
            old_name='emp_code',
            new_name='employee_code',
        ),
    ]
